### ISSUE TITLE
Tracking Issue for project rewrite

### ISSUE THREAD

**Issue by akabinds** [akabinds/prestige#1]
This is a tracking issue for the rewriting and restructuring of the Prestige project.

# Tasks
- [x] Transition back to `Limine` bootloader (to allow for future expansion into other architectures like `aarch64`)
- [x] Replace `Makefile` with a Python script that acts as the build system for the OS.
- [x] Implement testing framework.

*TASKS SUBJECT TO CHANGE*
